### ISSUE TITLE
'fix' action is missing in help text

### ISSUE THREAD

**Issue by memark** [grimmbraten/spinning-jenny#4]
According to the release notes for 3.0.0, there should be a "fix" action. This is not present in the help text.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/318504/143081960-72ea44bb-e1ee-4b58-aebc-893b295b2012.png">

**Comment by grimmbraten** [comment]
Thank you! The missed readme and `jenny --help actions` documentation updates has been resolved in version `3.0.1`
